language: elixir
elixir:
  - 1.2.6
  - 1.3.2
otp_release:
  - 18.3
  - 19.0
sudo: false # to use faster container based build environment
script:
  - mix deps.get
  - mix espec
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
